backend:
  name: github
  repo: monsieur17071707/portfolio-etudiant
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Articles du Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string", required: true }
      - { label: "Date", name: "date", widget: "datetime", format: "DD MMMM YYYY", required: true }
      - { label: "Catégorie", name: "categorie", widget: "select", options: ["Finance", "Gestion", "Divers"], required: true }
      - { label: "Résumé", name: "resume", widget: "text", required: true }
      - { label: "Contenu (Markdown)", name: "body", widget: "markdown", required: true }